### PR TITLE
New LEGO-Boost Firmware 2.0.00.0017 breaks pylgbst...

### PR DESCRIPTION
**Pull request by ijache**
Apologies for putting this in one commit:

I found pylgbst not working anymore after the most recent firmware-update for LEGO-Boost. After a little bit of research, i stumbled upon this:

https://github.com/LLK/scratch-vm/issues/2230 

Hence:
- I updated the port-numbers for the motors. ( 0x10 for MOTOR_AB was a guess, this one is not included in Scratch)
- I added a case for filtering LEGO-Boost devices without a mac-address. Seems to occur randomly. Trying to connect to device without a mac-address won't work.

Moreover i had a lot of trouble having pylgbst freezing randomly. I think i spotted a race-condition in Hub.send(): If its about a message that will receive a reply, the notification can come in before the _sync_lock is entered. 

Anyway: Thank you so much for putting this lib together!

### CODE REVIEW

**Comment by undera** [comment]
Hey, this is cool.
Can you look at unit tests, to fix the failure?

**Comment by undera** [comment]
Also, the change in port number will mean all Hubs with old firmware will not work properly anymore?

**Comment by ijache** [comment]
Ok, maybe this a little bit too quick:

1) Yes, old firmware wouldn't work. But i can look into this and set the port-numbers based on the firmware
2) I didn't look into why the tests are failing. Have to check on this too.

I will get back to you shortly, ok?

**Comment by undera** [comment]
Don't waste time with (1), it not worth it. Users of outdated hubs will always have a way to use generic Hub or subclass.

**Comment by ijache** [comment]
Ok, this is probably it. The tests were all failing due to the changed port numbers.  So the Python 2.7 tests all complete. But i can't really tell why the Python 3.4 test is failing. Can you have a look, please?

**Comment by undera** [comment]
3.4 issue seems to be on Travis side. I'm merging this PR, thanks for great contribution!

**Comment by ijache** [comment]
Thank you too!

**Pull request merged**
