### PR TITLE
Added test and fix for device matching

### PR DESCRIPTION
**Pull request by mdevel1**
This is my first pull request on github, please review my patches. :)

### CODE REVIEW

**Comment by undera** [comment]
Which problem does it fix?

**Comment by mdevel1** [comment]
When I have other BLE devices around (i.e. a Heart Rate Monitor, MAC changed in output), then the library can find it before pushing the green button on the Hub, causing an exception (master branch):
```
[2020-01-28 00:05:29,918] DEBUG::cbluepy::connect() Trying to connect client to MoveHub with MAC: None
[2020-01-28 00:05:29,919] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:05:30,939] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:05:31,962] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:05:32,985] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:05:34,008] DEBUG::__init__::_is_device_matched() Checking device name: HRM, MAC: 01:02:03:04:05:06
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    conn.connect()
  File "/home/test/build/pylgbst/pylgbst/comms/cbluepy.py", line 104, in connect
    if self._is_device_matched(address, name, hub_mac):
  File "/home/test/build/pylgbst/pylgbst/comms/__init__.py", line 52, in _is_device_matched
    if (not hub_mac and name == LEGO_MOVE_HUB) or hub_mac.lower() == address.lower():
AttributeError: 'NoneType' object has no attribute 'lower'
```

When I don't have other BLE devices around, and turn on the Hub, it is found with a full zero MAC a few times (only the real MAC changed in output)(master branch):
```
[2020-01-28 00:08:54,894] DEBUG::cbluepy::connect() Trying to connect client to MoveHub with MAC: None
[2020-01-28 00:08:54,894] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:08:55,915] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:08:56,943] DEBUG::__init__::_is_device_matched() Checking device name: LEGO Move Hub, MAC: 00:00:00:00:00:00
[2020-01-28 00:08:56,943] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:08:57,969] DEBUG::__init__::_is_device_matched() Checking device name: LEGO Move Hub, MAC: 00:00:00:00:00:00
[2020-01-28 00:08:57,969] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:08:58,993] DEBUG::__init__::_is_device_matched() Checking device name: LEGO Move Hub, MAC: 00:00:00:00:00:00
[2020-01-28 00:08:58,993] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:09:00,015] DEBUG::__init__::_is_device_matched() Checking device name: LEGO Move Hub, MAC: 00:00:00:00:00:00
[2020-01-28 00:09:00,015] DEBUG::__init__::_is_device_matched() Checking device name: LEGO Move Hub, MAC: 11:22:33:44:55:66
[2020-01-28 00:09:00,015] INFO::__init__::_is_device_matched() Found LEGO Move Hub at 11:22:33:44:55:66
[2020-01-28 00:09:00,017] DEBUG::cbluepy::write() Writing to handle 15: b'0100'
[2020-01-28 00:09:00,017] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:00,118] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:00,218] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:00,319] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:00,419] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:00,519] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:00,620] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:00,720] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:00,820] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:00,921] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:01,021] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:01,122] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:01,222] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:09:01,268] DEBUG::cbluepy::handleNotification() Incoming notification
[2020-01-28 00:09:01,269] DEBUG::hub::_notify() Notification on 14: b'0f0004000127000000001000000010'
[2020-01-28 00:09:01,269] DEBUG::hub::_get_upstream_msg() Decoded message: MsgHubAttachedIO({'payload': b'27000000001000000010', 'port': 0, 'event': 1})
[2020-01-28 00:09:01,270] DEBUG::hub::_notify() Handling msg with <bound method MoveHub._handle_device_change of <pylgbst.hub.MoveHub object at 0x7fe383c0e400>>: MsgHubAttachedIO({'payload': b'27000000001000000010', 'port': 0, 'event': 1})
[2020-01-28 00:09:01,271] INFO::hub::_handle_device_change() Attached peripheral: EncodedMotor on port 0x0
[2020-01-28 00:09:01,272] DEBUG::cbluepy::handleNotification() Incoming notification
[2020-01-28 00:09:01,272] DEBUG::hub::_notify() Notification on 14: b'0f0004010127000000001000000010'
[2020-01-28 00:09:01,272] DEBUG::hub::_get_upstream_msg() Decoded message: MsgHubAttachedIO({'payload': b'27000000001000000010', 'port': 1, 'event': 1})
[2020-01-28 00:09:01,272] DEBUG::hub::_notify() Handling msg with <bound method MoveHub._handle_device_change of <pylgbst.hub.MoveHub object at 0x7fe383c0e400>>: MsgHubAttachedIO({'payload': b'27000000001000000010', 'port': 1, 'event': 1})
```

But now I think the zero address check is needed, because it goes into an infinite loop with this exception without it (fix_1 branch):
```
[2020-01-28 00:13:35,851] DEBUG::cbluepy::connect() Trying to connect client to MoveHub with MAC: None
[2020-01-28 00:13:35,851] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:13:36,873] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:13:37,899] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:13:38,923] INFO::cbluepy::connect() Discovering devices...
[2020-01-28 00:13:39,948] DEBUG::__init__::_is_device_matched() Checking device name: LEGO Move Hub, MAC: 00:00:00:00:00:00
[2020-01-28 00:13:39,948] INFO::__init__::_is_device_matched() Found LEGO Move Hub at 00:00:00:00:00:00
[2020-01-28 00:13:39,949] DEBUG::cbluepy::write() Writing to handle 15: b'0100'
[2020-01-28 00:13:39,950] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:40,051] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:40,152] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:40,252] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:40,353] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:40,453] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:40,554] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:40,654] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:40,754] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:40,855] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:40,956] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:41,056] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:41,157] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:41,257] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:41,357] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:41,457] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:41,558] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:41,659] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:41,759] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:41,860] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:41,960] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:42,060] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:42,161] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:42,261] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:42,362] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:42,462] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:42,563] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:42,663] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:42,763] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:42,864] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:42,964] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:43,065] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:43,165] DEBUG::hub::_wait_for_devices() Waiting for builtin devices to appear: (None, None, None, None, None, None, None)
[2020-01-28 00:13:43,240] ERROR::cbluepy::_dispatch_calls() Exception in call dispatcher thread
Traceback (most recent call last):
  File "/home/test/build/pylgbst/pylgbst/comms/cbluepy.py", line 64, in _dispatch_calls
    self._peripheral.waitForNotifications(1.)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 560, in waitForNotifications
    resp = self._getResp(['ntfy','ind'], timeout)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 362, in _waitResp
    raise BTLEDisconnectError("Device disconnected", resp)
bluepy.btle.BTLEDisconnectError: Device disconnected
[2020-01-28 00:13:43,240] ERROR::cbluepy::_dispatch_calls() Exception in call dispatcher thread
Traceback (most recent call last):
  File "/home/test/build/pylgbst/pylgbst/comms/cbluepy.py", line 64, in _dispatch_calls
    self._peripheral.waitForNotifications(1.)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 560, in waitForNotifications
    resp = self._getResp(['ntfy','ind'], timeout)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 338, in _waitResp
    if self._helper.poll() is not None:
AttributeError: 'NoneType' object has no attribute 'poll'
[2020-01-28 00:13:43,240] ERROR::cbluepy::_dispatch_calls() Exception in call dispatcher thread
Traceback (most recent call last):
  File "/home/test/build/pylgbst/pylgbst/comms/cbluepy.py", line 64, in _dispatch_calls
    self._peripheral.waitForNotifications(1.)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 560, in waitForNotifications
    resp = self._getResp(['ntfy','ind'], timeout)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 338, in _waitResp
    if self._helper.poll() is not None:
AttributeError: 'NoneType' object has no attribute 'poll'
[2020-01-28 00:13:43,241] ERROR::cbluepy::_dispatch_calls() Exception in call dispatcher thread
Traceback (most recent call last):
  File "/home/test/build/pylgbst/pylgbst/comms/cbluepy.py", line 64, in _dispatch_calls
    self._peripheral.waitForNotifications(1.)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 560, in waitForNotifications
    resp = self._getResp(['ntfy','ind'], timeout)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 338, in _waitResp
    if self._helper.poll() is not None:
AttributeError: 'NoneType' object has no attribute 'poll'
[2020-01-28 00:13:43,241] ERROR::cbluepy::_dispatch_calls() Exception in call dispatcher thread
Traceback (most recent call last):
  File "/home/test/build/pylgbst/pylgbst/comms/cbluepy.py", line 64, in _dispatch_calls
    self._peripheral.waitForNotifications(1.)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 560, in waitForNotifications
    resp = self._getResp(['ntfy','ind'], timeout)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/home/test/.local/lib/python3.6/site-packages/bluepy/btle.py", line 338, in _waitResp
    if self._helper.poll() is not None:
AttributeError: 'NoneType' object has no attribute 'poll'
```

**Comment by mdevel1** [comment]
Updated the test to not match the zero address, and put back the check. I tried it now again with real hw, and works as expected.

**Comment by undera** [comment]
Thanks for explaining.
The only technical issue I see that single test does not justify introducing new external library "unittest2". Can you alter the test so it uses base unittest library?

**Comment by mdevel1** [comment]
Removed unittest2 dependency and features (subTest).
Left in a fixup commit for easier review, but it can be autosquashed.

**Comment by undera** [comment]
Thanks!

**Pull request merged**
