### PR TITLE
Introduce driver that works with Bleak

### PR DESCRIPTION
**Pull request by tomekmgr**
Adding a driver that use Bleak as a underlaying BLE infrastructure.
This enables usage of BLE devices without a need of additional dongle, 
If you have an BLE device in system and Windows see it it can be used for communication.

### CODE REVIEW

**Comment by undera** [comment]
This is great initiative! Can you please provide unit tests that will cover your code? It's important part of having project code stable for every release.

**Comment by tomekmgr** [comment]
> 
> 
> This is great initiative! Can you please provide unit tests that will cover your code? It's important part of having project code stable for every release.

Sure will try to add something, aldo getting 100% coverage will not be possible.
Another thing is to actually use that, we need install 'bleak' package on CI server, since I do not see requirments.txt how to do that ?

**Comment by undera** [comment]
The dependencies are to be specified right in setup.py: https://github.com/undera/pylgbst/blob/master/setup.py

Please use the `extras_require` section. I understand the 100% coverage is not easily possible, but some reasonable level is doable, just like all other project files have.

**Comment by undera** [comment]
Also, please consider adding some info into Readme.md, so people will know about the feature.

**Comment by undera** [comment]
Hm, I also noticed that your code is Python 3.7-specific due to details of asyncio usage. Currently, Ubuntu LTS ships Python 3.6, so ideally it should be supported. Or we should find another approach to this situation, where Bleak will be only invoked for Python 3.7+

**Comment by undera** [comment]
Ok, here we go: I managed to make tests runnable in this PR: https://github.com/undera/pylgbst/pull/55
Can you copy `.travis.yml` file into your PR? Then, we'll only need README.md to reflect the change, mention the instructions for users. With that, we'll have this improvement complete.

**Comment by undera** [comment]
I have merged my fixed version of this PR. Thanks!

**Pull request closed without merging**
